"use client";

import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import Link from 'next/link';

export default function BlogPost3() {
  return (
    <main>
      <Navbar />
      
      <section className="py-16 bg-gradient-to-b from-neutral to-base-100">
        <div className="retro-container">
          <div className="mb-8">
            <Link href="/blog" className="inline-block font-retro text-retroPink hover:text-retroYellow mb-4">
              ← BACK TO BLOG
            </Link>
            
            <h1 className="text-3xl md:text-4xl font-['Press_Start_2P'] mb-6 text-transparent bg-clip-text bg-gradient-to-r from-retroBlue to-retroPink">
              THE EVOLUTION OF CHIPTUNE MUSIC
            </h1>
            
            <div className="flex items-center mb-8">
              <div className="w-8 h-8 bg-retroPurple rounded-full border-2 border-white mr-2"></div>
              <span className="font-retro text-gray-300">By RetroWave Admin</span>
              <span className="mx-4 text-gray-400">|</span>
              <span className="font-retro text-gray-300">August 5, 2023</span>
            </div>
            
            <div className="aspect-video w-full bg-retroBlue bg-opacity-20 border-2 border-white mb-8 flex items-center justify-center">
              <div className="text-2xl font-['Press_Start_2P'] text-retroPink">FEATURED IMAGE</div>
            </div>
            
            <div className="retro-card p-8 mb-8">
              <div className="font-retro text-lg space-y-6">
                <p>
                  Before elaborate orchestral scores and licensed soundtracks became the norm in video games, developers worked within strict technical limitations to create memorable music using only simple sound waves. This was the birth of chiptune - a distinctive musical style generated by the sound chips in early computers and gaming consoles.
                </p>
                
                <h2 className="text-2xl font-[&quot;Press_Start_2P&quot;] text-retroYellow mt-8 mb-4">
                  TECHNICAL CONSTRAINTS
                </h2>
                
                <p>
                  The sound chips in early gaming hardware were extremely limited by today&apos;s standards. The Nintendo Entertainment System (NES), for example, could only produce three pulse waves, one triangle wave, one noise channel, and one sample channel simultaneously. These constraints forced composers to be extraordinarily creative with melody, rhythm, and implied harmony.
                </p>
                
                <p>
                  Despite these limitations - or perhaps because of them - game composers like Koji Kondo (Super Mario Bros), Hirokazu Tanaka (Metroid), and Tim Follin (Silver Surfer) created iconic soundtracks that players still remember decades later. The distinctive sound of these compositions became inextricably linked with the gaming experience.
                </p>
                
                <h2 className="text-2xl font-[&quot;Press_Start_2P&quot;] text-retroYellow mt-8 mb-4">
                  FROM NECESSITY TO AESTHETIC
                </h2>
                
                <p>
                  As technology advanced, the technical limitations that gave birth to chiptune music disappeared. Modern gaming hardware can reproduce high-fidelity orchestral recordings or any other sound imaginable. Yet something interesting happened - instead of abandoning the chiptune sound, many artists embraced it as a deliberate aesthetic choice.
                </p>
                
                <p>
                  Today, chiptune exists as a thriving music genre and community. Artists use original hardware, emulators, or specialized software to create new music in this distinctive style. Festivals dedicated to chiptune music draw enthusiastic crowds worldwide, and many indie games deliberately employ chiptune soundtracks to evoke nostalgia or create a specific atmosphere.
                </p>
                
                <h2 className="text-2xl font-[&quot;Press_Start_2P&quot;] text-retroYellow mt-8 mb-4">
                  CULTURAL IMPACT
                </h2>
                
                <p>
                  The influence of chiptune extends beyond gaming and niche music scenes. Its distinctive sounds have appeared in mainstream pop music, with artists like Kesha, Nicki Minaj, and Beck incorporating elements of the style into their hits. The simple yet distinctive sound of chiptune provides an instant connection to gaming culture and technological history.
                </p>
                
                <p>
                  For many, the appeal of chiptune lies in its unique intersection of constraints and creativity. In an era where digital music production offers virtually unlimited possibilities, there&apos;s something refreshing about art created within strict limitations - proof that innovation often thrives when boundaries exist.
                </p>
                
                <p>
                  Our retro gaming collection includes careful attention to authentic chiptune soundtracks, recreating the auditory experience that was such a crucial part of classic gaming.
                </p>
              </div>
            </div>
            
            <div className="flex justify-between items-center">
              <Link href="/blog" className="retro-button bg-retroBlue hover:bg-retroGreen">
                MORE ARTICLES
              </Link>
              
              <div className="flex space-x-4">
                <a href="#" className="w-10 h-10 flex items-center justify-center border-2 border-white bg-retroPurple">
                  <span className="font-retro">FB</span>
                </a>
                <a href="#" className="w-10 h-10 flex items-center justify-center border-2 border-white bg-retroPurple">
                  <span className="font-retro">TW</span>
                </a>
                <a href="#" className="w-10 h-10 flex items-center justify-center border-2 border-white bg-retroPurple">
                  <span className="font-retro">IG</span>
                </a>
              </div>
            </div>
          </div>
        </div>
      </section>
      
      <Footer />
    </main>
  );
} 